# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'DutchNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DutchNews
  # Reactive pods
  pod 'RxSwift', '~> 4.3.1'
  pod 'RxCocoa', '~> 4.3.1'
  # loading indicator
  pod 'PKHUD', '~> 5.2.0'
  
  #images
  pod 'Kingfisher', '~> 4.10.0'

  target 'DutchNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
